services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    environment:
      - 'MYSQL_DATABASE=distributed_task_db'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
    networks:
      - app-network

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - './data/redis-data:/data'
    command: redis-server --requirepass strong_password --appendonly yes
    networks:
      - app-network

  zoo1:
    image: 'zookeeper:3.9'
    hostname: 'zoo1'
    container_name: 'zoo1'
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: 'server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181'
    volumes:
      - './data/zoo1/data:/data'
      - './data/zoo1/logs:/datalog'
    networks:
      - app-network

  zoo2:
    image: 'zookeeper:3.9'
    hostname: 'zoo2'
    container_name: 'zoo2'
    ports:
      - '2182:2181'
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: 'server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181'
    volumes:
      - './data/zoo2/data:/data'
      - './data/zoo2/logs:/datalog'
    networks:
      - app-network

  zoo3:
    image: 'zookeeper:3.9'
    hostname: 'zoo3'
    container_name: 'zoo3'
    ports:
      - '2183:2181'
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: 'server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181'
    volumes:
      - './data/zoo3/data:/data'
      - './data/zoo3/logs:/datalog'
    networks:
      - app-network
  nginx:
    image: 'nginx:latest'
    container_name: 'nginx'
    ports:
      - '80:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - app-network
networks:
  app-network:
    driver: 'bridge'
